### ISSUE TITLE
Just wanna say...

### ISSUE THREAD

**Issue by boldandbusted** [wermajew/serverless-lambda-python-monorepo#1]
... thank you for this. Was just looking for some help determining the better approach for a Serverless Framework + Lambda + Python repo organization. Several references out there for NodeJS, but not for Python-centric projects. Cheers!

**Comment by weronika-malinowska-deltatre** [comment]
Thank you for the nice words. I felt the same when I was working with sls+lambda+python, not much resources online and sometimes we need to choose Python over NodeJS in our project. Cheers!
