### ISSUE TITLE
pyproject.toml differs between 'first' and 'second' directories

### ISSUE THREAD

**Issue by boldandbusted** [wermajew/serverless-lambda-python-monorepo#2]
Howdy. One file has the `pycommon = ...` assignment under `[tool.poetry.dev-dependencies]`, while the other has it under `[tool.poetry.dependencies]`. Is that intentional? (Apologies if it is.) Cheers.

**Comment by weronika-malinowska-deltatre** [comment]
Hi. Probably by accident. I think when the pycommon is used in prod code (and it's not some test utility etc. should be in [tool.poetry.dependencies] if it's not in prod code then [tool.poetry.dev-dependencies]. Similar to package.json -"dependencies" and "devDependencies". So in this case both should be under [tool.poetry.dependencies].
Cheers!
